import Head from 'next/head'
import BodyStyle from '../styles/body'
import Header from './Components/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Relatorios|Certificados</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodyStyle>
        <Header/>
        <h1>Home Page</h1>
        <img src="/home.jpg" alt="Image" />
      </BodyStyle>
    </>
  )
}
